# Site settings
title: Android Studio, Gradle, Dagger, Butter Knife, and Otto
email: btellez@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "http://blad.github.io/"
url: "http://blad.github.io"
twitter_username: bctellez
github_username:  blad

# Build settings
highlighter: pygments
markdown: kramdown
permalink: pretty
